name: Deploy

on:
  push:
    branches:
      - main

jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm i

      - run: npm run migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}